### ISSUE TITLE
window.py not running on window

### ISSUE THREAD

**Issue by Yiming828** [evanbrooks0629/surge#4]
when running window.py, this error happens.
E:\RKS\Supreme_bot\surge-master\surge-master>python window.py
Traceback (most recent call last):
  File "window.py", line 3127, in <module>
    checkStatus()
  File "window.py", line 3109, in checkStatus
    valid = isValid()
  File "window.py", line 3098, in isValid
    settings = settings_handler.get_all_settings()
  File "E:\RKS\Supreme_bot\surge-master\surge-master\handlers\settings_handler.py", line 35, in get_all_settings
    application_path.remove(application_path[6])
IndexError: list index out of range

**Comment by Yiming828** [comment]
i am trying to run on Window 10

**Comment by Yiming828** [comment]
OK, I solve issue
